# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.10 # optional, default is 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame==2.0.2 pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Building the game
        run: |
          # Compile the game 
          pyinstaller main.py -F --noconsole
        
