# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Compile for MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
          python-version: '3.10.0-alpha.1'
          
          
    - name: Installing Pygame 2.0.3 and compiling the game
      run: |
          python -m pip install pyinstaller pygame==2.0.3
          python -m PyInstaller build.spec

    - name: Commit Changes
      run: |          
        git add dist/*
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Executable for MacOS"
        git fetch origin main:tmp
        git rebase tmp
        git push origin HEAD:main
        git branch -D tmp

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: ${{ github.ref }}
      
