# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.10 in ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
          persist-credentials: false 
          python-version: '3.10.0-alpha.1'
          
    - name: Upgrade PIP and install Pygame 2.0.2
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller pygame==2.0.2
        
    - name: Compile Johns Adventure for ${{ matrix.os }}
      run: |
        python -m PyInstaller build.spec
        rm -rf build
        cv /dist/main /Executables/"Johns Adventure ${{ matrix.os }} 0.23"
        
    - name: Commit changes 
      run: |
        git status
        git add -A
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Executable file"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: ${{ github.ref }}
      
