# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Compile for Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.10
        uses: actions/setup-python@v2
        with:
          persist-credentials: false 
          python-version: '3.10.0-alpha.1'
          
      - name: Installing SDL2 + Pygame from Source
        run: |
            # Install dependencies
            sudo apt-get install git python3-dev python3-numpy \
                libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev \
                libsdl1.2-dev  libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev libfreetype6-dev
                
            sudo apt-get update
            sudo apt install --fix-missing

            # Grab source
            git clone git@github.com:pygame/pygame.git

            # Build pygame
            cd pygame
            python3 setup.py build

            # Create and activate the virtual environment
            mkvirtualenv NAME_OF_PROJECT --python=/usr/bin/python3
            workon NAME_OF_PROJECT

            # Install into the virtual environment
            python3 setup.py install  --prefix="$HOME/.virtualenvs/NAME_OF_PROJECT"
      - name: Installing PyInstaller 
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller 
      - name: Compiling the game
        run: |
          python -m PyInstaller build.spec
      - name: Commit changes 
        run: |
          git status
          git add -A
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Executable file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
      
