# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.10 in Ubuntu
        uses: actions/setup-python@v2
        with:
          persist-credentials: false 
          python-version: '3.10.0-alpha.1'
          
      - name: Upgrade PIP,Building SDL2 and install Pygame 2.0.2
        run: |
          sudo apt-get update
          sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev python3-setuptools python3-dev python3 libportmidi-dev
          sudo apt-get build-dep libsdl2 libsdl2-image libsdl2-mixer libsdl2-ttf libfreetype6 python3 libportmidi0
          sudo cp /etc/apt/sources.list /etc/apt/sources.list~
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get upgrade
          git clone https://github.com/pygame/pygame.git
          cd pygame
          python3 setup.py -config -auto -sdl2
          python3 setup.py install --user
          python -m pip install --upgrade pip
          python -m pip install pyinstaller 
          
      - name: Compiling the game
        run: |
          python -m PyInstaller build.spec
          sudo rm -rf build
          cv /dist/main /dist/"John's Adventure Linux V0.23"

      - name: Commit changes 
        run: |
          git status
          git add -A
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Executable file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
      
