name: Compile for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.10 in Windows
        uses: actions/setup-python@v2
        with:
          persist-credentials: false 
          python-version: '3.10.0-alpha.1'
          
      - name: Installing Pygame 2.0.3 and compiling the game
        run: |
          python -m pip install pyinstaller pygame==2.0.3
          python -m PyInstaller build.spec

      - name: Commit changes 
        run: |          
          git add dist/*
          git status
